# Generated by Django 3.1.7 on 2021-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210308_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_number',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('topic', 'post_number'), name='unique_topic_post_num'),
        ),
    ]
